// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NFLFantasyChallenge.Models;

#nullable disable

namespace NFLFantasyChallenge.Migrations
{
    [DbContext(typeof(FantasyDbContext))]
    [Migration("20260207171143_AddChallengeRules")]
    partial class AddChallengeRules
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("NFLFantasyChallenge.Models.ChallengeRule", b =>
                {
                    b.Property<int>("ChallengeRuleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ChallengeRuleId");

                    b.ToTable("ChallengeRules");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.Lineup", b =>
                {
                    b.Property<int>("LineupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DefenseId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KickerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QbId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("QbId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RbId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RbId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RbId3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RbId4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RbId5")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TeId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrId1")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrId2")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrId3")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrId4")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WrId5")
                        .HasColumnType("INTEGER");

                    b.HasKey("LineupId");

                    b.HasIndex("DefenseId");

                    b.HasIndex("KickerId");

                    b.HasIndex("QbId1");

                    b.HasIndex("QbId2");

                    b.HasIndex("RbId1");

                    b.HasIndex("RbId2");

                    b.HasIndex("RbId3");

                    b.HasIndex("RbId4");

                    b.HasIndex("RbId5");

                    b.HasIndex("TeId1");

                    b.HasIndex("TeId2");

                    b.HasIndex("UserId");

                    b.HasIndex("WrId1");

                    b.HasIndex("WrId2");

                    b.HasIndex("WrId3");

                    b.HasIndex("WrId4");

                    b.HasIndex("WrId5");

                    b.ToTable("Lineups");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.Player", b =>
                {
                    b.Property<int>("PlayerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ConferenceScore")
                        .HasColumnType("REAL");

                    b.Property<double?>("DivisionalScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("SuperBowlScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("WildcardScore")
                        .HasColumnType("REAL");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("PlayerId");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Balance")
                        .HasColumnType("REAL");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.Lineup", b =>
                {
                    b.HasOne("NFLFantasyChallenge.Models.Player", "Defense")
                        .WithMany()
                        .HasForeignKey("DefenseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Kicker")
                        .WithMany()
                        .HasForeignKey("KickerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Qb1")
                        .WithMany()
                        .HasForeignKey("QbId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Qb2")
                        .WithMany()
                        .HasForeignKey("QbId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Rb1")
                        .WithMany()
                        .HasForeignKey("RbId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Rb2")
                        .WithMany()
                        .HasForeignKey("RbId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Rb3")
                        .WithMany()
                        .HasForeignKey("RbId3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Rb4")
                        .WithMany()
                        .HasForeignKey("RbId4")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Rb5")
                        .WithMany()
                        .HasForeignKey("RbId5")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Te1")
                        .WithMany()
                        .HasForeignKey("TeId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Te2")
                        .WithMany()
                        .HasForeignKey("TeId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Wr1")
                        .WithMany()
                        .HasForeignKey("WrId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Wr2")
                        .WithMany()
                        .HasForeignKey("WrId2")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Wr3")
                        .WithMany()
                        .HasForeignKey("WrId3")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Wr4")
                        .WithMany()
                        .HasForeignKey("WrId4")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NFLFantasyChallenge.Models.Player", "Wr5")
                        .WithMany()
                        .HasForeignKey("WrId5")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Defense");

                    b.Navigation("Kicker");

                    b.Navigation("Qb1");

                    b.Navigation("Qb2");

                    b.Navigation("Rb1");

                    b.Navigation("Rb2");

                    b.Navigation("Rb3");

                    b.Navigation("Rb4");

                    b.Navigation("Rb5");

                    b.Navigation("Te1");

                    b.Navigation("Te2");

                    b.Navigation("User");

                    b.Navigation("Wr1");

                    b.Navigation("Wr2");

                    b.Navigation("Wr3");

                    b.Navigation("Wr4");

                    b.Navigation("Wr5");
                });

            modelBuilder.Entity("NFLFantasyChallenge.Models.User", b =>
                {
                    b.HasOne("NFLFantasyChallenge.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
